version: '3.3'

services:

  # adminer:
  #   image: adminer
  #   container_name: ehiot-mysql-adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"

  node-red:
    restart: always
    container_name: ehiot-node-red
    build: 
      context: ./nodered
      dockerfile: Dockerfile
    # environment:
    #   - TZ=Europe/Amsterdam
    #   - MYSQLUSERNAME=root
    #   - MYSQLPASSWORD=example
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data 

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/data 
    environment:
      - INFLUXDB_DB=EHIOT
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/data 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${INFLUXDB_USERNAME}


