version: '3.3'

services:

  node-red:
    restart: always
    container_name: ehiot-node-red
    build: 
      context: ./nodered
      dockerfile: Dockerfile
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data 

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_DB=EHIOT
      - DOCKER_INFLUXDB_INIT_BUCKET=Data_EHIOT
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=UNIVAQ
      # - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      # - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana:rw
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${INFLUXDB_USERNAME}


